primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 32432
  initdb:
    scripts:
      create-surogates.sql: |
        CREATE USER surogates WITH PASSWORD 'surogates';
        CREATE DATABASE surogates OWNER surogates;
