apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: surogate-default
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
images:
  - name: camofox-browser
    newName: camofox-browser
    newTag: latest
