apiVersion: v1
kind: Secret
metadata:
  name: camofox-browser-secret
  namespace: surogate-default
type: Opaque
stringData:
  CAMOFOX_ACCESS_KEY: replace-me
  CAMOFOX_API_KEY: replace-me
  CAMOFOX_ADMIN_KEY: replace-me
  VNC_PASSWORD: replace-me
