import type { AgentChatEventType } from "../types";

export const WORKSPACE_MUTATING_TOOLS: ReadonlySet<string> = new Set([
  "terminal",
  "write_file",
  "patch",
  "execute_code",
  "browser_screenshot",
]);

export const AGENT_CHAT_LISTENED_EVENTS = [
  "user.message",
  "llm.request",
  "llm.response",
  "llm.thinking",
  "llm.delta",
  "tool.call",
  "tool.result",
  "session.start",
  "session.pause",
  "session.resume",
  "session.complete",
  "session.fail",
  "session.done",
  "harness.wake",
  "harness.crash",
  "context.compact",
  "skill.invoked",
  "policy.denied",
  "stream.timeout",
  "expert.result",
  "expert.endorse",
  "expert.override",
  "user.feedback",
  "artifact.created",
  "artifact.updated",
  "browser.provisioned",
  "browser.destroyed",
  "browser.control_granted",
  "browser.control_returned",
  "clarify.response",
] as const satisfies readonly AgentChatEventType[];
