import type { AgentChatEventType } from "../types";

export const AGENT_CHAT_LISTENED_EVENTS = [
  "user.message",
  "llm.request",
  "llm.response",
  "llm.thinking",
  "llm.delta",
  "tool.call",
  "tool.result",
  "session.start",
  "session.pause",
  "session.resume",
  "session.complete",
  "session.fail",
  "session.done",
  "harness.wake",
  "harness.crash",
  "context.compact",
  "skill.invoked",
  "policy.denied",
  "stream.timeout",
  "expert.result",
  "expert.endorse",
  "expert.override",
  "artifact.created",
  "artifact.updated",
  "clarify.response",
] as const satisfies readonly AgentChatEventType[];
